version: '3.8'
services:
  nodejs:
    image: nuxt-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/frontend
      - /var/www/frontend/node_modules
    command: npm run generate

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - nodejs