version: '3.8'
services:
  nuxtApp:
    image: nuxt-app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - nuxtApp